spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
          - id: accounts-api
            uri: lb://accounts-service
            predicates:
              - Path=/api/v1/users/**     

          - id: cash-api
            uri: lb://cash-service
            predicates:
              - Path=/api/v1/cash/**

          - id: transfer-api
            uri: lb://transfer-service
            predicates:
              - Path=/api/v1/transfers/**

          - id: notifications-api
            uri: lb://notifications-service
            predicates:
              - Path=/api/v1/notifications/**

          - id: auth-api
            uri: lb://auth-service
            predicates: [ Path=/auth/** ]
            filters: [ StripPrefix=1 ]  

          - id: front-ui
            uri: lb://front-ui-service
            predicates:
              - Path=/ui/**
            filters:
              - StripPrefix=1 
          # - id: exchange-api
          #   uri: lb://exchange-service
          #   predicates: - Path=/exchange/**
          #- id: exchange-generation-api
          #   uri: lb://exchange-generation-service
          #   predicates: Path=/exgen**
          # - id: blocker-api
          #   uri: lb://blocker-service
          #   predicates: Path=/blocker**

          - id: accounts-docs
            uri: lb://accounts-service
            predicates:
              - Path=/accounts-service/**
            filters:
            - StripPrefix=1

          - id: cash-docs
            uri: lb://cash-service
            predicates:
             - Path=/cash-service/**
            filters:
             - StripPrefix=1

          - id: transfer-docs
            uri: lb://transfer-service
            predicates:
              - Path=/transfer-service/**
            filters:
              - StripPrefix=1

          - id: notifications-docs
            uri: lb://notifications-service
            predicates:
              - Path=/notifications-service/**
            filters:
              - StripPrefix=1

          - id: front-ui-docs
            uri: lb://front-ui-service
            predicates:
              - Path=/front-ui-service/**
            filters:
              - StripPrefix=1

    # - id: exchange-docs
    #   uri: lb://exchange-service
    #   predicates: [ Path=/exchange-service/v3/api-docs ]
    #   filters: [ StripPrefix=1 ]
    # - id: exchange-generation-docs
    #   uri: lb://exchange-generation-service
    #   predicates: [ Path=/exchange-generation-service/v3/api-docs ]
    #   filters: [ StripPrefix=1 ]
    # - id: blocker-docs
    #   uri: lb://blocker-service
    #   predicates: [ Path=/blocker-service/v3/api-docs ]
    #   filters: [ StripPrefix=1 ]
springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui
      urls:
        - name: Accounts
          url: /accounts-service/v3/api-docs
        - name: Cash
          url: /cash-service/v3/api-docs
        - name: Transfer
          url: /transfer-service/v3/api-docs
        - name: Notifications
          url: /notifications-service/v3/api-docs
        - name: Front-UI
          url: /front-ui-service/v3/api-docs
      # - name: Exchange
      #   url: /exchange-service/v3/api-docs
      # - name: Exchange generation
      #   url: /exchange-generation-service/v3/api-docs
      # - name: Blocker
      #   url: /blocker-service/v3/api-docs  
security:
    oauth2:
      client:
        registration:
          svc:
            provider: as
            client-id: gateway-client
            client-secret: ${GATEWAY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          as:
            token-uri: http://localhost:8080/auth/oauth2/token

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops,loggers,gateway,refresh            
