# === Eureka ===
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
# === Springdoc (Swagger) ===
springdoc:
  api-doc:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
# === Notifications client ===
notifications:
  client:
    path: /api/v1/notifications 
# === Actuator ===
management:
  endpoints.web.exposure.include: health,info,metrics,env,configprops,loggers
  endpoint.health.show-details: always    
