spring:
  application:
    name: notifications-service

  datasource:
    url: jdbc:postgresql://postgres:5432/bank?currentSchema=notifications
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    
  sql:
    init:
      mode: always
      schema-locations: classpath:db/init_notifications_schema.sql
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER} 
management:
  endpoints:
    web:
      exposure:
        include: health,info
