data:
    MANAGEMENT_TRACING_ENABLED: "true"
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://infra-zipkin:9411/api/v2/spans"

    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"
    MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
    MANAGEMENT_METRICS_TAGS_APPLICATION: "${spring.application.name}"

    OBSERVABILITY_METRICS_CARDINALITY_GUARD_ENABLED: "true"
    OBSERVABILITY_METRICS_ALLOW_USERNAME_TAG: "false"