apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-infra-prometheus
  labels:
    {{- include "infra-prometheus.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-infra-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-infra-prometheus
    namespace: {{ .Release.Namespace }}
