apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-infra-prometheus
  labels:
    {{- include "infra-prometheus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: infra-prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 9090 }}
      targetPort: http
      protocol: TCP
