<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>ru.practicum</groupId>
	<artifactId>bank-app</artifactId>
	<version>0.0.2-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>bank-app</name>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.3</version>
		<relativePath />
	</parent>

	<modules>
		<module>auth-service</module>
		<module>accounts-service</module>
		<module>cash-service</module>
		<module>transfer-service</module>
		<module>notifications-service</module>
		<module>front-ui-service</module>
		<module>blocker-service</module>
		<module>exchange-service</module>
		<module>exchange-generation-service</module>
		<module>platform-contracts</module>
		<module>platform-notifications-client-starter</module>
		<module>platform-web-exception-starter</module>
		<module>platform-http-client-starter</module>
		<module>platform-security-starter</module>
		<module>platform-kafka-starter</module>
	</modules>

	<properties>
		<java.version>21</java.version>
		<springdoc.version>2.6.0</springdoc.version>
		<testcontainers.version>1.20.2</testcontainers.version>
		<restassured.version>5.5.0</restassured.version>
		<wiremock.version>3.9.1</wiremock.version>
		<flyway.version>10.20.1</flyway.version>
		<resilience4j.version>2.2.0</resilience4j.version>
		<micrometer.tracing.version>1.6.0</micrometer.tracing.version>
		<zipkin.reporter.brave.version>3.5.1</zipkin.reporter.brave.version>
		<micrometer-prometheus.version>1.13.0</micrometer-prometheus.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<!-- Tests dependencies -->
			<dependency>
				<groupId>org.testcontainers</groupId>
				<artifactId>testcontainers-bom</artifactId>
				<version>${testcontainers.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			
			<dependency>
				<groupId>org.flywaydb</groupId>
				<artifactId>flyway-core</artifactId>
				<version>${flyway.version}</version>
			</dependency>

			<dependency>
				<groupId>io.github.resilience4j</groupId>
				<artifactId>resilience4j-spring-boot3</artifactId>
				<version>${resilience4j.version}</version>
			</dependency>
			
			<dependency>
				<groupId>io.micrometer</groupId>
				<artifactId>micrometer-tracing-bridge-brave</artifactId>
				<version>${micrometer.tracing.version}</version>
			</dependency>
			
			<dependency>
				<groupId>io.zipkin.reporter2</groupId>
				<artifactId>zipkin-reporter-brave</artifactId>
				<version>${zipkin.reporter.brave.version}</version>
			</dependency>
			
			<dependency>
				<groupId>io.micrometer</groupId>
				<artifactId>micrometer-registry-prometheus</artifactId>
				<version>${micrometer-prometheus.version}</version>
			</dependency>
			
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.2.5</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-failsafe-plugin</artifactId>
					<version>3.2.5</version>
				</plugin>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
