apiVersion: v2
name: infra-zipkin
description: Zipkin tracing service for bank-app
type: application
version: 0.1.0

dependencies:
  - name: service-template
    version: 0.1.0
    repository: "file://../service-template"