server:
  port: 8085

spring:
  application:
    name: cash-service
  config:
    import: "configserver:http://config-server:8888"

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh