package ru.practicum.platform.contracts.enums;

public enum NotificationEvent {
	USER_UPDATED,
    USER_PASSWORD_CHANGED,
    ACCOUNT_CREATED, ACCOUNT_UPDATED, ACCOUNT_DELETED,
    CASH_DEPOSITED, CASH_WITHDRAWN,
    TRANSFER_CREATED, TRANSFER_COMPLETED, TRANSFER_FAILED

}
