server:
  port: 8086

spring:
  application:
    name: blocker-service
  config:
    import: 
      - "optional:configserver:"
      - "optional:file:./secrets.yml"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
