elasticsearch:
  enabled: true
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch"
    tag: "8.18.4"
    pullPolicy: IfNotPresent
  replicas: 1
  port: 9200
  resources: {}
  storage:
    enabled: true
    size: 2Gi
    storageClassName: ""
  javaOpts: "-Xms512m -Xmx512m"

logstash:
  enabled: true
  image:
    repository: "docker.elastic.co/logstash/logstash"
    tag: "8.18.4"
    pullPolicy: IfNotPresent
  replicas: 1
  port: 5044
  resources: {}
  pipeline: ""  

kibana:
  enabled: true
  image:
    repository: "docker.elastic.co/kibana/kibana"
    tag: "8.18.4"
    pullPolicy: IfNotPresent
  replicas: 1
  port: 5601
  resources: {}
  service:
    type: ClusterIP
  ingress:
    enabled: false
    className: nginx
    hosts: []
    tls: []
