grafana:
  enabled: true

  image:
    repository: "docker.io/grafana/grafana"
    tag: "11.1.0"
    pullPolicy: IfNotPresent

  replicas: 1
  port: 3000

  adminUser: "admin"
  adminPassword: "admin"   # secret, 

  service:
    type: ClusterIP

  ingress:
    enabled: false
    className: nginx
    hosts: []
    tls: []

  prometheus:
    url: "http://infra-prometheus:9090"

  resources: {}

probes:
  liveness:
    enabled: false   
    path: /api/health
    initialDelaySeconds: 20
    periodSeconds: 10
  readiness:
    enabled: false
    path: /api/health
    initialDelaySeconds: 10
    periodSeconds: 5

monitoring:
  enabled: false    
