{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra-elk.fullname" . }}-kibana
  labels:
    {{- include "infra-elk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kibana.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/component: kibana
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.kibana.port | default 5601 }}
      targetPort: http
      protocol: TCP
{{- end }}
